export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const NO_EXECUTE_PERMISSION = 'NO_EXECUTE_PERMISSION';
export const PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED';
export const OLD_PASSWORD_IS_NOT_CORRECT = 'OLD_PASSWORD_IS_NOT_CORRECT';
export const NEW_PASSWORD_MUST_BE_DIFFERENT_OLD_PASSWORD =
  'NEW_PASSWORD_MUST_BE_DIFFERENT_OLD_PASSWORD';
export const FOLLOW_IDS_IS_REQUIRED = 'FOLLOW_IDS_IS_REQUIRED';
export const USERNAME_OR_PASSWORD_INCORRECT = 'USERNAME_OR_PASSWORD_INCORRECT';
export const ERROR_UPLOAD_CDN = 'ERROR_UPLOAD_CDN';
export const CANT_EDIT_ONCE_PUBLISHED = 'CANT_EDIT_ONCE_PUBLISHED';
